name: Solidity

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Copyright notice
      run: |
        .scripts/check-copyright-notice.sh
        .scripts/check-notice-authors.sh origin/master

    - name: Dependencies
      run: |
        git submodule update --init --recursive
        sudo apt-get install python3-setuptools -y
        sudo -H pip3 install slither-analyzer
        sudo -H npm install -g truffle@5.1.46 typescript solhint

    - uses: bahmutov/npm-install@v1

    - name: Solhint
      run: solhint "contracts/**/*.sol"

    - name: Test
      run: |
        yarn build
        npm test

    - name: Coverage
      run: truffle run coverage

    - name: Slither
      run: |
        solc-select 0.7.4
        slither --exclude solc-version,timestamp,boolean-equality,unimplemented-functions,locked-ether --filter-paths vendor/ .
